import { useState, useRef } from "react";
import { motion, AnimatePresence } from "motion/react";
import { UploadCloud, Eye, Zap, Camera, ScanFace, Image as ImageIcon, Video } from "lucide-react";

export function Deepfake() {
  const [file, setFile] = useState<File | null>(null);
  const [status, setStatus] = useState<"idle" | "uploading" | "scanning" | "result">("idle");
  const [score, setScore] = useState(0);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleUploadClick = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      setStatus("uploading");
      setTimeout(() => {
        setStatus("scanning");
        setTimeout(() => {
          setStatus("result");
          setScore(Math.floor(Math.random() * 40) + 60); // Random score indicating high likelihood of deepfake
        }, 3000);
      }, 1500);
    }
  };

  const reset = () => {
    setStatus("idle");
    setFile(null);
    setScore(0);
  };

  return (
    <div className="min-h-screen pt-32 pb-20 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto flex flex-col items-center">
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-16 w-full"
      >
        <ScanFace className="w-16 h-16 text-cyan-400 mx-auto mb-6" />
        <h1 className="text-4xl md:text-6xl font-black text-white mb-6 tracking-tight">
          Deepfake Detector
        </h1>
        <p className="text-xl text-neutral-400 max-w-2xl mx-auto">
          Upload an image or video to reveal invisible alterations and synthetic artifacts generated by AI models.
        </p>
      </motion.div>

      <div className="w-full max-w-4xl relative min-h-[500px] flex items-center justify-center">
        <AnimatePresence mode="wait">
          {status === "idle" && (
            <motion.div
              key="idle"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9, filter: "blur(10px)" }}
              transition={{ duration: 0.4 }}
              className="w-full bg-neutral-900 border-2 border-dashed border-neutral-700 hover:border-cyan-500 rounded-3xl p-12 text-center cursor-pointer transition-colors group relative overflow-hidden"
              onClick={handleUploadClick}
            >
              <div className="absolute inset-0 bg-cyan-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
              
              <input
                type="file"
                ref={fileInputRef}
                className="hidden"
                accept="image/*,video/*"
                onChange={handleFileChange}
              />
              
              <UploadCloud className="w-24 h-24 text-neutral-600 group-hover:text-cyan-400 transition-colors mx-auto mb-8" />
              
              <h3 className="text-3xl font-bold text-white mb-4">Drag & drop media</h3>
              <p className="text-neutral-500 text-lg mb-8">
                or click to browse your files (JPG, PNG, MP4)
              </p>
              
              <div className="flex justify-center gap-6">
                <div className="flex items-center gap-2 text-neutral-400 bg-neutral-950 px-4 py-2 rounded-xl border border-neutral-800">
                  <ImageIcon className="w-5 h-5 text-indigo-400" /> Image Mode
                </div>
                <div className="flex items-center gap-2 text-neutral-400 bg-neutral-950 px-4 py-2 rounded-xl border border-neutral-800">
                  <Video className="w-5 h-5 text-pink-400" /> Video Mode
                </div>
              </div>
            </motion.div>
          )}

          {status === "uploading" && (
            <motion.div
              key="uploading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col items-center justify-center w-full"
            >
              <div className="w-full max-w-md bg-neutral-900 h-4 rounded-full overflow-hidden mb-6 border border-neutral-800">
                <motion.div
                  initial={{ width: "0%" }}
                  animate={{ width: "100%" }}
                  transition={{ duration: 1.5, ease: "easeInOut" }}
                  className="h-full bg-cyan-500"
                />
              </div>
              <p className="text-xl text-cyan-400 font-medium animate-pulse">
                Uploading securely...
              </p>
            </motion.div>
          )}

          {status === "scanning" && (
            <motion.div
              key="scanning"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 1.1 }}
              className="w-full h-full relative"
            >
              <div className="relative rounded-3xl overflow-hidden border border-neutral-800 mx-auto w-full max-w-2xl bg-neutral-950 aspect-video flex items-center justify-center group">
                {/* Mock file preview background */}
                <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80')] bg-cover bg-center opacity-40 blur-sm grayscale" />
                
                {/* Scanning line */}
                <motion.div
                  initial={{ top: "-10%" }}
                  animate={{ top: "110%" }}
                  transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                  className="absolute left-0 right-0 h-1 bg-cyan-400 shadow-[0_0_20px_5px_rgba(34,211,238,0.5)] z-20"
                />

                <div className="absolute inset-0 z-10 grid grid-cols-6 grid-rows-4">
                  {[...Array(24)].map((_, i) => (
                    <motion.div
                      key={i}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: [0, 0.5, 0] }}
                      transition={{ duration: 1, repeat: Infinity, delay: Math.random() * 2 }}
                      className="border border-cyan-500/20"
                    />
                  ))}
                </div>

                <div className="relative z-30 flex flex-col items-center text-center">
                  <Zap className="w-12 h-12 text-cyan-400 animate-pulse mb-4" />
                  <h3 className="text-2xl font-bold text-white tracking-widest">
                    ANALYZING ARTIFACTS
                  </h3>
                  <p className="text-cyan-500 font-mono mt-2">Checking spatial frequencies...</p>
                </div>
              </div>
            </motion.div>
          )}

          {status === "result" && (
            <motion.div
              key="result"
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              className="w-full flex flex-col md:flex-row gap-12"
            >
              <div className="flex-1 relative rounded-3xl overflow-hidden border border-neutral-800 bg-neutral-900 group aspect-square md:aspect-auto h-[400px]">
                <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80')] bg-cover bg-center transition-all duration-700 filter" />
                
                {/* Overlay heatmap mock */}
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 0.6 }}
                  transition={{ delay: 0.5, duration: 2 }}
                  className="absolute inset-0 bg-gradient-to-tr from-transparent via-red-500/40 to-transparent mix-blend-overlay"
                />
                
                {/* Detected points mock */}
                {[
                  { top: '30%', left: '40%' },
                  { top: '50%', left: '60%' },
                  { top: '70%', left: '45%' },
                ].map((pos, i) => (
                  <motion.div
                    key={i}
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ delay: 1 + (i * 0.2), type: "spring" }}
                    className="absolute w-12 h-12 rounded-full border-2 border-red-500 shadow-[0_0_15px_rgba(239,68,68,0.8)]"
                    style={{ top: pos.top, left: pos.left, x: '-50%', y: '-50%' }}
                  >
                    <div className="absolute top-full left-1/2 -translate-x-1/2 mt-2 bg-neutral-900 border border-red-500/50 text-red-400 text-xs px-2 py-1 rounded">
                      Anomaly {(i+1)}
                    </div>
                  </motion.div>
                ))}
              </div>

              <div className="flex-1 flex flex-col justify-center">
                <div className="bg-neutral-900 border border-red-500/30 rounded-3xl p-8 mb-8 relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-red-500/5 rounded-bl-full" />
                  <Eye className="w-12 h-12 text-red-500 mb-6" />
                  <h2 className="text-4xl font-black text-white mb-2 tracking-tight">AI Generated</h2>
                  <p className="text-xl text-neutral-400 mb-8">
                    High probability of synthetic manipulation detected in facial structures.
                  </p>
                  
                  <div className="space-y-6">
                    <div>
                      <div className="flex justify-between mb-2">
                        <span className="text-neutral-300 font-medium">Synthetic Probability</span>
                        <span className="text-red-400 font-bold">{score}%</span>
                      </div>
                      <div className="w-full bg-neutral-950 h-3 rounded-full overflow-hidden">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${score}%` }}
                          transition={{ duration: 1.5, ease: "circOut" }}
                          className="h-full bg-gradient-to-r from-amber-500 to-red-500"
                        />
                      </div>
                    </div>
                    
                    <div>
                      <div className="flex justify-between mb-2">
                        <span className="text-neutral-300 font-medium">Spatial Inconsistencies</span>
                        <span className="text-red-400 font-bold">High</span>
                      </div>
                      <div className="w-full bg-neutral-950 h-3 rounded-full overflow-hidden">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `85%` }}
                          transition={{ duration: 1.5, delay: 0.2, ease: "circOut" }}
                          className="h-full bg-red-500"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={reset}
                  className="w-full py-4 rounded-xl bg-neutral-800 hover:bg-neutral-700 text-white font-bold transition-colors border border-neutral-700 flex items-center justify-center gap-2"
                >
                  <Camera className="w-5 h-5" />
                  Scan Another File
                </motion.button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
