from pathlib import Path
import argparse
import json
import sys

import joblib
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_fscore_support
from sklearn.pipeline import Pipeline

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Retrain the fake-news model in data-size increments until a target accuracy is reached."
    )
    parser.add_argument(
        "--train-file",
        default=str(ROOT / "data" / "processed" / "full" / "train.csv"),
        help="Training CSV generated by scripts\\prepare_data.py",
    )
    parser.add_argument(
        "--validation-file",
        default=str(ROOT / "data" / "processed" / "full" / "val.csv"),
        help="Validation CSV generated by scripts\\prepare_data.py",
    )
    parser.add_argument(
        "--test-file",
        default=str(ROOT / "data" / "processed" / "full" / "test.csv"),
        help="Test CSV generated by scripts\\prepare_data.py",
    )
    parser.add_argument(
        "--output-dir",
        default=str(ROOT / "models" / "fakenewsnet_tfidf"),
        help="Directory for the final model bundle and metrics report.",
    )
    parser.add_argument(
        "--target-accuracy",
        type=float,
        default=0.90,
        help="Stop once test accuracy meets or exceeds this threshold.",
    )
    parser.add_argument(
        "--increment-size",
        type=float,
        default=0.10,
        help="Fractional train-size increase per round, e.g. 0.10 for 10%% increments.",
    )
    parser.add_argument(
        "--max-fraction",
        type=float,
        default=1.0,
        help="Maximum training fraction to try before stopping.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for subset sampling and model training.",
    )
    return parser.parse_args()


def confidence_summary(labels: np.ndarray, predictions: np.ndarray, confidences: np.ndarray) -> dict[str, float]:
    correct_mask = labels == predictions
    summary = {
        "average_confidence": float(confidences.mean()) if len(confidences) else 0.0,
        "median_confidence": float(np.median(confidences)) if len(confidences) else 0.0,
        "minimum_confidence": float(confidences.min()) if len(confidences) else 0.0,
        "maximum_confidence": float(confidences.max()) if len(confidences) else 0.0,
        "average_confidence_when_correct": 0.0,
        "average_confidence_when_incorrect": 0.0,
        "fake_prediction_rate": float((predictions == 0).mean()) if len(predictions) else 0.0,
        "real_prediction_rate": float((predictions == 1).mean()) if len(predictions) else 0.0,
    }
    if correct_mask.any():
        summary["average_confidence_when_correct"] = float(confidences[correct_mask].mean())
    if (~correct_mask).any():
        summary["average_confidence_when_incorrect"] = float(confidences[~correct_mask].mean())
    return summary


def evaluate(pipe: Pipeline, frame: pd.DataFrame) -> dict:
    labels = frame["label"].to_numpy(dtype=int)
    probabilities = pipe.predict_proba(frame["combined_text"])
    class_to_index = {int(label): index for index, label in enumerate(pipe.named_steps["clf"].classes_)}
    fake_scores = probabilities[:, class_to_index[0]]
    real_scores = probabilities[:, class_to_index[1]]
    predictions = np.where(fake_scores >= real_scores, 0, 1)
    confidences = np.maximum(fake_scores, real_scores)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="binary",
        zero_division=0,
        pos_label=0,
    )
    return {
        "accuracy": float(accuracy_score(labels, predictions)),
        "precision_fake": float(precision),
        "recall_fake": float(recall),
        "f1_fake": float(f1),
        "confusion_matrix": confusion_matrix(labels, predictions).tolist(),
        "confidence": confidence_summary(labels, predictions, confidences),
    }


def build_pipeline(seed: int) -> Pipeline:
    return Pipeline(
        [
            (
                "tfidf",
                TfidfVectorizer(
                    lowercase=True,
                    strip_accents="unicode",
                    ngram_range=(1, 2),
                    min_df=2,
                    max_df=0.98,
                    sublinear_tf=True,
                ),
            ),
            (
                "clf",
                LogisticRegression(
                    max_iter=2000,
                    class_weight="balanced",
                    random_state=seed,
                ),
            ),
        ]
    )


def sample_training_frame(frame: pd.DataFrame, fraction: float, seed: int) -> pd.DataFrame:
    if fraction >= 1.0:
        return frame.sample(frac=1.0, random_state=seed).reset_index(drop=True)

    sampled_parts = []
    for label in sorted(frame["label"].unique()):
        label_frame = frame.loc[frame["label"] == label]
        sample_size = max(1, int(round(len(label_frame) * fraction)))
        sampled_parts.append(label_frame.sample(n=min(sample_size, len(label_frame)), random_state=seed))
    sampled = pd.concat(sampled_parts, ignore_index=True)
    return sampled.sample(frac=1.0, random_state=seed).reset_index(drop=True)


def main() -> None:
    args = parse_args()
    train_df = pd.read_csv(args.train_file)
    val_df = pd.read_csv(args.validation_file)
    test_df = pd.read_csv(args.test_file)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    history: list[dict] = []
    best_bundle: Pipeline | None = None
    best_report: dict | None = None
    best_accuracy = -1.0

    increment = max(args.increment_size, 0.01)
    fractions = np.arange(increment, min(args.max_fraction, 1.0) + 0.0001, increment)
    if not np.isclose(fractions[-1], min(args.max_fraction, 1.0)):
        fractions = np.append(fractions, min(args.max_fraction, 1.0))

    for index, fraction in enumerate(fractions, start=1):
        sampled_train = sample_training_frame(train_df, float(fraction), seed=args.seed)
        pipeline = build_pipeline(seed=args.seed)
        pipeline.fit(sampled_train["combined_text"], sampled_train["label"])

        validation_metrics = evaluate(pipeline, val_df)
        test_metrics = evaluate(pipeline, test_df)
        report = {
            "increment": index,
            "train_fraction": round(float(fraction), 4),
            "train_rows": int(len(sampled_train)),
            "validation": validation_metrics,
            "test_metrics": test_metrics,
        }
        history.append(report)
        print(json.dumps(report, indent=2))

        if test_metrics["accuracy"] > best_accuracy:
            best_accuracy = float(test_metrics["accuracy"])
            best_bundle = pipeline
            best_report = report

        if test_metrics["accuracy"] >= args.target_accuracy:
            break

    if best_bundle is None or best_report is None:
        raise RuntimeError("Training did not produce any model bundle.")

    joblib.dump(best_bundle, output_dir / "model.joblib")

    def to_portable_path(path_value: str) -> str:
        path = Path(path_value)
        try:
            relative = path.resolve().relative_to(ROOT)
        except Exception:
            return str(path)
        return relative.as_posix()

    training_config = {
        "model_name": "tfidf-logreg-fakenewsnet",
        "model_type": "sklearn_tfidf_logreg",
        "train_file": to_portable_path(args.train_file),
        "validation_file": to_portable_path(args.validation_file),
        "test_file": to_portable_path(args.test_file),
        "text_column": "combined_text",
        "label_column": "label",
        "output_dir": to_portable_path(str(output_dir)),
        "max_length": 0,
        "seed": args.seed,
        "target_accuracy": args.target_accuracy,
        "increment_size": args.increment_size,
    }
    (output_dir / "training_config.json").write_text(
        json.dumps(training_config, indent=2),
        encoding="utf-8",
    )

    final_report = {
        "device": "cpu",
        "train_rows": best_report["train_rows"],
        "validation_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "history": history,
        "test_metrics": best_report["test_metrics"],
        "best_increment": best_report["increment"],
        "best_train_fraction": best_report["train_fraction"],
    }
    (output_dir / "metrics.json").write_text(json.dumps(final_report, indent=2), encoding="utf-8")

    print("\nFinal summary:")
    print(json.dumps(final_report, indent=2))


if __name__ == "__main__":
    main()
